algoritmo "conteAteUsuario"
// Função :
// Autor :
// Data : 01/04/2020
// Seção de Declarações 
var
   valor, contador : inteiro

inicio
      contador <- 0
      Escreva("Quer contar até quanto? ")
      Leia(valor)
      EscrevaL("")
      Enquanto (contador <= valor) faca
              EscrevaL(contador)
              contador <- contador + 1 // aqui o contador recebe ele + 1
      FimEnquanto
      EscrevaL("")
      EscrevaL("Terminei de contar!!!")
// Seção de Comandos 
fimalgoritmo
