algoritmo "fazSomaProcedimento"

// Função : fazer soma com parametros
// Autor : Joice CP
// Data : 06/04/2020

var

  x, y : inteiro


Procedimento Soma(A, B: inteiro)
inicio

  EscrevaL("Recebi o valor", A)
  EscrevaL("Recebi o valor", B)
  EscrevaL("A soma entre eles é" A + B)

FimProcedimento

inicio

  x <- 5
  y <= 3
  Soma(x, y) //o valor de X vai ser copiado pra A, e o valor de Y para B

fimalgoritmo
