Algoritmo "ParOuImpar"

//Função: Identificar e o número é par ou impar, utilizando a estrutura de condição 1 - composta (se-senão)
//Autor: Joice CP
//Data: 24/03/2020

Var

   N : inteiro

Inicio

      Escreva("Digite um número: ")
      Leia(N)
      Se (N % 2 = 0) então
         EscrevaL ("O número", N, " é um número PAR")
      Senao
         EscrevaL ("O número", N, " é um número IMPAR")
      FimSe

Fimalgoritmo
