algoritmo "somaFuncao"

// Função : soma com função
// Autor : Joice
// Data : 06/04/2020

var

   valor1, valor2, S : inteiro

Funcao Soma(X, Y : inteiro) : inteiro

inicio

     Retorne (X + Y) //pode fazer direto

FimFuncao

inicio

   Escreva("Digite o primeiro valor: ")
   Leia(valor1)
   Escreva("")
   Escreva("Digite o segundo valor: ")
   Leia(valor2)
   
   S <- Soma (valor1, valor2)

   EscrevaL("")
   EscrevaL("A soma entre", valor1, " e", valor2, " é igual a", S)

   
fimalgoritmo
