algoritmo "valoresInicioEFim"

// Função : Identificar valores pares, utilizando a estrutura de repetição 3 (PARA)
// Autor : Joice CP
// Data : 05/04/2020

var

   contador, valorInicio, valorFim  : inteiro

inicio

   Escreva("Digite um valor: ")
   Leia(valorInicio)
   EscrevaL("")
   Escreva("Digite outro valor: ")
   Leia(valorFim)
   EscrevaL("")
   
   Para contador <- valorInicio ate valorFim faca
        Escreva(contador, "...")
   FimPara
   
   EscrevaL("")

fimalgoritmo
